/*
 * This file was automatically generated by EvoSuite
 * Wed Jun 03 10:39:10 GMT 2026
 */

package org.apache.openjpa.jdbc.meta;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.security.PrivilegedActionException;
import org.apache.openjpa.jdbc.meta.ClassMapping;
import org.apache.openjpa.jdbc.meta.Discriminator;
import org.apache.openjpa.jdbc.meta.FieldMapping;
import org.apache.openjpa.jdbc.meta.MappingDefaults;
import org.apache.openjpa.jdbc.meta.MappingRepository;
import org.apache.openjpa.jdbc.meta.QueryResultMapping;
import org.apache.openjpa.jdbc.meta.RuntimeStrategyInstaller;
import org.apache.openjpa.jdbc.meta.StrategyInstaller;
import org.apache.openjpa.jdbc.meta.ValueMapping;
import org.apache.openjpa.jdbc.meta.ValueMappingImpl;
import org.apache.openjpa.jdbc.meta.Version;
import org.apache.openjpa.jdbc.meta.strats.CharArrayStreamValueHandler;
import org.apache.openjpa.jdbc.meta.strats.NanoPrecisionTimestampVersionStrategy;
import org.apache.openjpa.jdbc.meta.strats.StateComparisonVersionStrategy;
import org.apache.openjpa.jdbc.meta.strats.SubclassJoinDiscriminatorStrategy;
import org.apache.openjpa.jdbc.meta.strats.XMLValueHandler;
import org.apache.openjpa.jdbc.schema.SchemaGroup;
import org.apache.openjpa.lib.log.LogFactoryImpl;
import org.apache.openjpa.meta.ClassMetaData;
import org.apache.openjpa.meta.FieldMetaData;
import org.apache.openjpa.meta.Order;
import org.apache.openjpa.meta.ValueMetaData;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;


@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true)
public class MappingRepository_ESTest {

    @Test(timeout = 4000)
    public void test00()  throws Throwable  {
        MappingRepository mappingRepository0 = new MappingRepository();
        RuntimeStrategyInstaller runtimeStrategyInstaller0 = new RuntimeStrategyInstaller(mappingRepository0);
        // Undeclared exception!
        try {
            runtimeStrategyInstaller0.installStrategy((Discriminator) null);
            fail("Expecting exception: NullPointerException");

        } catch(NullPointerException e) {
            //
            // no message in exception (getMessage() returned null)
            //
            verifyException("org.apache.openjpa.jdbc.meta.MappingRepository", e);
        }
    }

    @Test(timeout = 4000)
    public void test01()  throws Throwable  {
        MappingRepository mappingRepository0 = new MappingRepository();
        Order[] orderArray0 = mappingRepository0.newOrderArray(2731);
        assertEquals(2731, orderArray0.length);
        assertEquals(7, mappingRepository0.getValidate());
    }

    @Test(timeout = 4000)
    public void test02()  throws Throwable  {
        MappingRepository mappingRepository0 = new MappingRepository();
        FieldMetaData[] fieldMetaDataArray0 = mappingRepository0.newFieldMetaDataArray(33);
        assertEquals(33, fieldMetaDataArray0.length);
        assertEquals(7, mappingRepository0.getValidate());
    }

    @Test(timeout = 4000)
    public void test03()  throws Throwable  {
        MappingRepository mappingRepository0 = new MappingRepository();
        ClassMetaData[] classMetaDataArray0 = mappingRepository0.newClassMetaDataArray(50200);
        assertEquals(7, mappingRepository0.getValidate());
        assertEquals(50200, classMetaDataArray0.length);
    }

    @Test(timeout = 4000)
    public void test04()  throws Throwable  {
        MappingRepository mappingRepository0 = new MappingRepository();
        Class<Object> class0 = Object.class;
        mappingRepository0.getMapping(class0, (ClassLoader) null, false);
        assertEquals(7, mappingRepository0.getValidate());
    }

    @Test(timeout = 4000)
    public void test05()  throws Throwable  {
        MappingRepository mappingRepository0 = new MappingRepository();
        // Undeclared exception!
        try {
            mappingRepository0.setDefaultInheritanceStrategy((ClassMapping) null);
            fail("Expecting exception: NullPointerException");

        } catch(NullPointerException e) {
            //
            // no message in exception (getMessage() returned null)
            //
            verifyException("org.apache.openjpa.jdbc.meta.MappingRepository", e);
        }
    }

    @Test(timeout = 4000)
    public void test06()  throws Throwable  {
        MappingRepository mappingRepository0 = new MappingRepository();
        // Undeclared exception!
        try {
            mappingRepository0.prepareMapping((ClassMetaData) null);
            fail("Expecting exception: NullPointerException");

        } catch(NullPointerException e) {
            //
            // no message in exception (getMessage() returned null)
            //
            verifyException("org.apache.openjpa.jdbc.meta.MappingRepository", e);
        }
    }

    @Test(timeout = 4000)
    public void test07()  throws Throwable  {
        MappingRepository mappingRepository0 = new MappingRepository();
        // Undeclared exception!
        try {
            mappingRepository0.newFieldMetaDataArray((-2));
            fail("Expecting exception: NegativeArraySizeException");

        } catch(NegativeArraySizeException e) {
            //
            // no message in exception (getMessage() returned null)
            //
            verifyException("org.apache.openjpa.jdbc.meta.MappingRepository", e);
        }
    }

    @Test(timeout = 4000)
    public void test08()  throws Throwable  {
        MappingRepository mappingRepository0 = new MappingRepository();
        // Undeclared exception!
        try {
            mappingRepository0.namedStrategy((Version) null);
            fail("Expecting exception: NullPointerException");

        } catch(NullPointerException e) {
            //
            // no message in exception (getMessage() returned null)
            //
            verifyException("org.apache.openjpa.jdbc.meta.MappingRepository", e);
        }
    }

    @Test(timeout = 4000)
    public void test09()  throws Throwable  {
        MappingRepository mappingRepository0 = new MappingRepository();
        // Undeclared exception!
        try {
            mappingRepository0.namedStrategy((FieldMapping) null, true);
            fail("Expecting exception: NullPointerException");

        } catch(NullPointerException e) {
            //
            // no message in exception (getMessage() returned null)
            //
            verifyException("org.apache.openjpa.jdbc.meta.MappingRepository", e);
        }
    }

    @Test(timeout = 4000)
    public void test10()  throws Throwable  {
        MappingRepository mappingRepository0 = new MappingRepository();
        // Undeclared exception!
        try {
            mappingRepository0.namedHandler((ValueMapping) null);
            fail("Expecting exception: NullPointerException");

        } catch(NullPointerException e) {
            //
            // no message in exception (getMessage() returned null)
            //
            verifyException("org.apache.openjpa.jdbc.meta.MappingRepository", e);
        }
    }

    @Test(timeout = 4000)
    public void test11()  throws Throwable  {
        MappingRepository mappingRepository0 = new MappingRepository();
        // Undeclared exception!
        try {
            mappingRepository0.isUniMTo1JT((FieldMapping) null);
            fail("Expecting exception: NullPointerException");

        } catch(NullPointerException e) {
            //
            // no message in exception (getMessage() returned null)
            //
            verifyException("org.apache.openjpa.jdbc.meta.MappingRepository", e);
        }
    }

    @Test(timeout = 4000)
    public void test12()  throws Throwable  {
        MappingRepository mappingRepository0 = new MappingRepository();
        // Undeclared exception!
        try {
            mappingRepository0.isUni1ToMFK((FieldMapping) null);
            fail("Expecting exception: NullPointerException");

        } catch(NullPointerException e) {
            //
            // no message in exception (getMessage() returned null)
            //
            verifyException("org.apache.openjpa.jdbc.meta.MappingRepository", e);
        }
    }

    @Test(timeout = 4000)
    public void test13()  throws Throwable  {
        MappingRepository mappingRepository0 = new MappingRepository();
        // Undeclared exception!
        try {
            mappingRepository0.isBidirectional((FieldMapping) null);
            fail("Expecting exception: NullPointerException");

        } catch(NullPointerException e) {
            //
            // no message in exception (getMessage() returned null)
            //
            verifyException("org.apache.openjpa.jdbc.meta.MappingRepository", e);
        }
    }

    @Test(timeout = 4000)
    public void test14()  throws Throwable  {
        MappingRepository mappingRepository0 = new MappingRepository();
        // Undeclared exception!
        try {
            mappingRepository0.isBiMTo1JT((FieldMapping) null);
            fail("Expecting exception: NullPointerException");

        } catch(NullPointerException e) {
            //
            // no message in exception (getMessage() returned null)
            //
            verifyException("org.apache.openjpa.jdbc.meta.MappingRepository", e);
        }
    }

    @Test(timeout = 4000)
    public void test15()  throws Throwable  {
        MappingRepository mappingRepository0 = new MappingRepository();
        // Undeclared exception!
        try {
            mappingRepository0.isBi1To1JT((FieldMapping) null);
            fail("Expecting exception: NullPointerException");

        } catch(NullPointerException e) {
            //
            // no message in exception (getMessage() returned null)
            //
            verifyException("org.apache.openjpa.jdbc.meta.MappingRepository", e);
        }
    }

    @Test(timeout = 4000)
    public void test16()  throws Throwable  {
        MappingRepository mappingRepository0 = new MappingRepository();
        // Undeclared exception!
        try {
            mappingRepository0.hasJoinTable((FieldMapping) null);
            fail("Expecting exception: NullPointerException");

        } catch(NullPointerException e) {
            //
            // no message in exception (getMessage() returned null)
            //
            verifyException("org.apache.openjpa.jdbc.meta.MappingRepository", e);
        }
    }

    @Test(timeout = 4000)
    public void test17()  throws Throwable  {
        MappingRepository mappingRepository0 = new MappingRepository();
        // Undeclared exception!
        try {
            mappingRepository0.hasJoinColumn((FieldMapping) null);
            fail("Expecting exception: NullPointerException");

        } catch(NullPointerException e) {
            //
            // no message in exception (getMessage() returned null)
            //
            verifyException("org.apache.openjpa.jdbc.meta.MappingRepository", e);
        }
    }

    @Test(timeout = 4000)
    public void test18()  throws Throwable  {
        MappingRepository mappingRepository0 = new MappingRepository();
        // Undeclared exception!
        try {
            mappingRepository0.hasInheritanceStrategy((ClassMapping) null);
            fail("Expecting exception: NullPointerException");

        } catch(NullPointerException e) {
            //
            // no message in exception (getMessage() returned null)
            //
            verifyException("org.apache.openjpa.jdbc.meta.MappingRepository", e);
        }
    }

    @Test(timeout = 4000)
    public void test19()  throws Throwable  {
        MappingRepository mappingRepository0 = new MappingRepository();
        CharArrayStreamValueHandler charArrayStreamValueHandler0 = new CharArrayStreamValueHandler();
        // Undeclared exception!
        try {
            mappingRepository0.handlerCollectionStrategy((FieldMapping) null, charArrayStreamValueHandler0, false);
            fail("Expecting exception: NullPointerException");

        } catch(NullPointerException e) {
            //
            // no message in exception (getMessage() returned null)
            //
            verifyException("org.apache.openjpa.jdbc.meta.MappingRepository", e);
        }
    }

    @Test(timeout = 4000)
    public void test20()  throws Throwable  {
        MappingRepository mappingRepository0 = new MappingRepository();
        ClassLoader classLoader0 = ClassLoader.getSystemClassLoader();
        // Undeclared exception!
        try {
            mappingRepository0.getMapping((Object) null, classLoader0, true);
            fail("Expecting exception: RuntimeException");

        } catch(RuntimeException e) {
            //
            // Could not locate metadata for the class using oid \"null\" of type \"?\".  Registered oid type mappings: \"java.util.Collections$SynchronizedMap@0000000003\"
            //
            verifyException("org.apache.openjpa.meta.MetaDataRepository", e);
        }
    }

    @Test(timeout = 4000)
    public void test21()  throws Throwable  {
        MappingRepository mappingRepository0 = new MappingRepository();
        Class<Character> class0 = Character.TYPE;
        // Undeclared exception!
        try {
            mappingRepository0.getMapping(class0, (ClassLoader) null, true);
            fail("Expecting exception: RuntimeException");

        } catch(RuntimeException e) {
            //
            // No metadata was found for type \"char\". The class is not enhanced.
            //
            verifyException("org.apache.openjpa.meta.MetaDataRepository", e);
        }
    }

    @Test(timeout = 4000)
    public void test22()  throws Throwable  {
        MappingRepository mappingRepository0 = new MappingRepository();
        // Undeclared exception!
        try {
            mappingRepository0.getBi_MTo1_JoinTableField((FieldMapping) null);
            fail("Expecting exception: NullPointerException");

        } catch(NullPointerException e) {
            //
            // no message in exception (getMessage() returned null)
            //
            verifyException("org.apache.openjpa.jdbc.meta.MappingRepository", e);
        }
    }

    @Test(timeout = 4000)
    public void test23()  throws Throwable  {
        MappingRepository mappingRepository0 = new MappingRepository();
        // Undeclared exception!
        try {
            mappingRepository0.getBi_1ToM_JoinTableField((FieldMapping) null);
            fail("Expecting exception: NullPointerException");

        } catch(NullPointerException e) {
            //
            // no message in exception (getMessage() returned null)
            //
            verifyException("org.apache.openjpa.jdbc.meta.MappingRepository", e);
        }
    }

    @Test(timeout = 4000)
    public void test24()  throws Throwable  {
        MappingRepository mappingRepository0 = new MappingRepository();
        // Undeclared exception!
        try {
            mappingRepository0.findBaseClassMapping((ClassMapping) null);
            fail("Expecting exception: NullPointerException");

        } catch(NullPointerException e) {
            //
            // no message in exception (getMessage() returned null)
            //
            verifyException("org.apache.openjpa.jdbc.meta.MappingRepository", e);
        }
    }

    @Test(timeout = 4000)
    public void test25()  throws Throwable  {
        MappingRepository mappingRepository0 = new MappingRepository();
        // Undeclared exception!
        try {
            mappingRepository0.endConfiguration();
            fail("Expecting exception: NullPointerException");

        } catch(NullPointerException e) {
            //
            // no message in exception (getMessage() returned null)
            //
            verifyException("org.apache.openjpa.meta.MetaDataRepository", e);
        }
    }

    @Test(timeout = 4000)
    public void test26()  throws Throwable  {
        MappingRepository mappingRepository0 = new MappingRepository();
        // Undeclared exception!
        try {
            mappingRepository0.defaultStrategy((Version) null, false);
            fail("Expecting exception: NullPointerException");

        } catch(NullPointerException e) {
            //
            // no message in exception (getMessage() returned null)
            //
            verifyException("org.apache.openjpa.jdbc.meta.MappingRepository", e);
        }
    }

    @Test(timeout = 4000)
    public void test27()  throws Throwable  {
        MappingRepository mappingRepository0 = new MappingRepository();
        // Undeclared exception!
        try {
            mappingRepository0.defaultStrategy((FieldMapping) null, false, false);
            fail("Expecting exception: NullPointerException");

        } catch(NullPointerException e) {
            //
            // no message in exception (getMessage() returned null)
            //
            verifyException("org.apache.openjpa.jdbc.meta.MappingRepository", e);
        }
    }

    @Test(timeout = 4000)
    public void test28()  throws Throwable  {
        MappingRepository mappingRepository0 = new MappingRepository();
        // Undeclared exception!
        try {
            mappingRepository0.defaultStrategy((Discriminator) null, false);
            fail("Expecting exception: NullPointerException");

        } catch(NullPointerException e) {
            //
            // no message in exception (getMessage() returned null)
            //
            verifyException("org.apache.openjpa.jdbc.meta.MappingRepository", e);
        }
    }

    @Test(timeout = 4000)
    public void test29()  throws Throwable  {
        MappingRepository mappingRepository0 = new MappingRepository();
        // Undeclared exception!
        try {
            mappingRepository0.defaultStrategy((ClassMapping) null, false);
            fail("Expecting exception: NullPointerException");

        } catch(NullPointerException e) {
            //
            // no message in exception (getMessage() returned null)
            //
            verifyException("org.apache.openjpa.jdbc.meta.MappingRepository", e);
        }
    }

    @Test(timeout = 4000)
    public void test30()  throws Throwable  {
        MappingRepository mappingRepository0 = new MappingRepository();
        StrategyInstaller strategyInstaller0 = mappingRepository0.getStrategyInstaller();
        assertEquals(7, mappingRepository0.getValidate());
        assertNotNull(strategyInstaller0);
    }

    @Test(timeout = 4000)
    public void test31()  throws Throwable  {
        MappingRepository mappingRepository0 = new MappingRepository();
        Class<XMLValueHandler> class0 = XMLValueHandler.class;
        // Undeclared exception!
        try {
            mappingRepository0.instantiateVersionStrategy(class0, (Version) null, "kuk~J 7(CJ9pP;@.)");
            fail("Expecting exception: NullPointerException");

        } catch(NullPointerException e) {
            //
            // no message in exception (getMessage() returned null)
            //
            verifyException("org.apache.openjpa.jdbc.meta.MappingRepository", e);
        }
    }

    @Test(timeout = 4000)
    public void test32()  throws Throwable  {
        MappingRepository mappingRepository0 = new MappingRepository();
        // Undeclared exception!
        try {
            mappingRepository0.instantiateVersionStrategy("CmMbuGVHuf<0$}", (Version) null);
            fail("Expecting exception: NullPointerException");

        } catch(NullPointerException e) {
            //
            // no message in exception (getMessage() returned null)
            //
            verifyException("org.apache.openjpa.jdbc.meta.MappingRepository", e);
        }
    }

    @Test(timeout = 4000)
    public void test33()  throws Throwable  {
        MappingRepository mappingRepository0 = new MappingRepository();
        // Undeclared exception!
        try {
            mappingRepository0.instantiateClassStrategy("`syn", (ClassMapping) null);
            fail("Expecting exception: RuntimeException");

        } catch(RuntimeException e) {
            //
            // Could not instantiate custom class strategy \"`syn\" for type \"null\".  Make sure this is a valid ClassStrategy implementation.
            //
            verifyException("org.apache.openjpa.jdbc.meta.MappingRepository", e);
        }
    }

    @Test(timeout = 4000)
    public void test34()  throws Throwable  {
        MappingRepository mappingRepository0 = new MappingRepository();
        // Undeclared exception!
        try {
            mappingRepository0.clear();
            fail("Expecting exception: NullPointerException");

        } catch(NullPointerException e) {
            //
            // no message in exception (getMessage() returned null)
            //
            verifyException("org.apache.openjpa.meta.MetaDataRepository", e);
        }
    }

    @Test(timeout = 4000)
    public void test35()  throws Throwable  {
        MappingRepository mappingRepository0 = new MappingRepository();
        boolean boolean0 = mappingRepository0.removeQueryResultMapping((QueryResultMapping) null);
        assertFalse(boolean0);
        assertEquals(7, mappingRepository0.getValidate());
    }

    @Test(timeout = 4000)
    public void test36()  throws Throwable  {
        MappingRepository mappingRepository0 = new MappingRepository();
        Class<StateComparisonVersionStrategy> class0 = StateComparisonVersionStrategy.class;
        boolean boolean0 = mappingRepository0.removeQueryResultMapping(class0, (String) null);
        assertEquals(7, mappingRepository0.getValidate());
        assertFalse(boolean0);
    }

    @Test(timeout = 4000)
    public void test37()  throws Throwable  {
        MappingRepository mappingRepository0 = new MappingRepository();
        Class<StateComparisonVersionStrategy> class0 = StateComparisonVersionStrategy.class;
        boolean boolean0 = mappingRepository0.removeQueryResultMapping(class0, "omzvGD");
        assertEquals(7, mappingRepository0.getValidate());
        assertFalse(boolean0);
    }

    @Test(timeout = 4000)
    public void test38()  throws Throwable  {
        MappingRepository mappingRepository0 = new MappingRepository();
        Class<Character> class0 = Character.TYPE;
        QueryResultMapping queryResultMapping0 = mappingRepository0.addQueryResultMapping(class0, ";7R+Yt.(M\"ZUC*dG");
        boolean boolean0 = mappingRepository0.removeQueryResultMapping(queryResultMapping0);
        assertTrue(boolean0);
        assertEquals(7, mappingRepository0.getValidate());
    }

    @Test(timeout = 4000)
    public void test39()  throws Throwable  {
        MappingRepository mappingRepository0 = new MappingRepository();
        mappingRepository0.getQueryResultMappings();
        assertEquals(7, mappingRepository0.getValidate());
    }

    @Test(timeout = 4000)
    public void test40()  throws Throwable  {
        MappingRepository mappingRepository0 = new MappingRepository();
        Class<QueryResultMapping> class0 = QueryResultMapping.class;
        ClassLoader classLoader0 = ClassLoader.getSystemClassLoader();
        // Undeclared exception!
        try {
            mappingRepository0.getQueryResultMapping(class0, "version-numbers", classLoader0, true);
            fail("Expecting exception: NullPointerException");

        } catch(NullPointerException e) {
            //
            // no message in exception (getMessage() returned null)
            //
            verifyException("org.apache.openjpa.meta.MetaDataRepository", e);
        }
    }

    @Test(timeout = 4000)
    public void test41()  throws Throwable  {
        MappingRepository mappingRepository0 = new MappingRepository();
        RuntimeStrategyInstaller runtimeStrategyInstaller0 = new RuntimeStrategyInstaller(mappingRepository0);
        mappingRepository0.setStrategyInstaller(runtimeStrategyInstaller0);
        assertEquals(7, mappingRepository0.getValidate());
    }

    @Test(timeout = 4000)
    public void test42()  throws Throwable  {
        MappingRepository mappingRepository0 = new MappingRepository();
        SchemaGroup schemaGroup0 = new SchemaGroup();
        mappingRepository0.setSchemaGroup(schemaGroup0);
        assertEquals(7, mappingRepository0.getValidate());
    }

    @Test(timeout = 4000)
    public void test43()  throws Throwable  {
        MappingRepository mappingRepository0 = new MappingRepository();
        // Undeclared exception!
        try {
            mappingRepository0.getSchemaGroup();
            fail("Expecting exception: NullPointerException");

        } catch(NullPointerException e) {
            //
            // no message in exception (getMessage() returned null)
            //
            verifyException("org.apache.openjpa.jdbc.meta.MappingRepository", e);
        }
    }

    @Test(timeout = 4000)
    public void test44()  throws Throwable  {
        MappingRepository mappingRepository0 = new MappingRepository();
        mappingRepository0.newMappingInfo((Version) null);
        assertEquals(7, mappingRepository0.getValidate());
    }

    @Test(timeout = 4000)
    public void test45()  throws Throwable  {
        MappingRepository mappingRepository0 = new MappingRepository();
        // Undeclared exception!
        try {
            mappingRepository0.newValueMetaData((FieldMetaData) null);
            fail("Expecting exception: NullPointerException");

        } catch(NullPointerException e) {
            //
            // no message in exception (getMessage() returned null)
            //
            verifyException("org.apache.openjpa.jdbc.meta.ValueMappingImpl", e);
        }
    }

    @Test(timeout = 4000)
    public void test46()  throws Throwable  {
        MappingRepository mappingRepository0 = new MappingRepository();
        ClassMapping[] classMappingArray0 = mappingRepository0.getMappings();
        assertEquals(7, mappingRepository0.getValidate());
        assertEquals(0, classMappingArray0.length);
    }

    @Test(timeout = 4000)
    public void test47()  throws Throwable  {
        MappingRepository mappingRepository0 = new MappingRepository();
        // Undeclared exception!
        try {
            mappingRepository0.newRelatedFieldOrder((FieldMetaData) null, (FieldMetaData) null, false);
            fail("Expecting exception: NullPointerException");

        } catch(NullPointerException e) {
            //
            // no message in exception (getMessage() returned null)
            //
            verifyException("org.apache.openjpa.jdbc.meta.JDBCRelatedFieldOrder", e);
        }
    }

    @Test(timeout = 4000)
    public void test48()  throws Throwable  {
        MappingRepository mappingRepository0 = new MappingRepository();
        // Undeclared exception!
        try {
            mappingRepository0.defaultStrategy((ClassMapping) null);
            fail("Expecting exception: NullPointerException");

        } catch(NullPointerException e) {
            //
            // no message in exception (getMessage() returned null)
            //
            verifyException("org.apache.openjpa.jdbc.meta.MappingRepository", e);
        }
    }

    @Test(timeout = 4000)
    public void test49()  throws Throwable  {
        MappingRepository mappingRepository0 = new MappingRepository();
        // Undeclared exception!
        try {
            mappingRepository0.defaultStrategy((FieldMapping) null, false);
            fail("Expecting exception: NullPointerException");

        } catch(NullPointerException e) {
            //
            // no message in exception (getMessage() returned null)
            //
            verifyException("org.apache.openjpa.jdbc.meta.MappingRepository", e);
        }
    }

    @Test(timeout = 4000)
    public void test50()  throws Throwable  {
        MappingRepository mappingRepository0 = new MappingRepository();
        mappingRepository0.getMappingDefaults();
        assertEquals(7, mappingRepository0.getValidate());
    }

    @Test(timeout = 4000)
    public void test51()  throws Throwable  {
        MappingRepository mappingRepository0 = new MappingRepository();
        ValueMappingImpl valueMappingImpl0 = new ValueMappingImpl();
        // Undeclared exception!
        try {
            mappingRepository0.defaultHandler(valueMappingImpl0);
            fail("Expecting exception: NullPointerException");

        } catch(NullPointerException e) {
            //
            // no message in exception (getMessage() returned null)
            //
            verifyException("org.apache.openjpa.jdbc.meta.MappingRepository", e);
        }
    }

    @Test(timeout = 4000)
    public void test52()  throws Throwable  {
        MappingRepository mappingRepository0 = new MappingRepository();
        // Undeclared exception!
        try {
            mappingRepository0.namedStrategy((ClassMapping) null);
            fail("Expecting exception: NullPointerException");

        } catch(NullPointerException e) {
            //
            // no message in exception (getMessage() returned null)
            //
            verifyException("org.apache.openjpa.jdbc.meta.MappingRepository", e);
        }
    }

    @Test(timeout = 4000)
    public void test53()  throws Throwable  {
        MappingRepository mappingRepository0 = new MappingRepository();
        SubclassJoinDiscriminatorStrategy subclassJoinDiscriminatorStrategy0 = new SubclassJoinDiscriminatorStrategy();
        ClassLoader classLoader0 = ClassLoader.getSystemClassLoader();
        // Undeclared exception!
        try {
            mappingRepository0.getMapping((Object) subclassJoinDiscriminatorStrategy0, classLoader0, false);
            fail("Expecting exception: NullPointerException");

        } catch(NullPointerException e) {
            //
            // no message in exception (getMessage() returned null)
            //
            verifyException("org.apache.openjpa.meta.MetaDataRepository", e);
        }
    }

    @Test(timeout = 4000)
    public void test54()  throws Throwable  {
        MappingRepository mappingRepository0 = new MappingRepository();
        // Undeclared exception!
        try {
            mappingRepository0.isNonDefaultMappingAllowed();
            fail("Expecting exception: NullPointerException");

        } catch(NullPointerException e) {
            //
            // no message in exception (getMessage() returned null)
            //
            verifyException("org.apache.openjpa.jdbc.meta.MappingRepository", e);
        }
    }

    @Test(timeout = 4000)
    public void test55()  throws Throwable  {
        MappingRepository mappingRepository0 = new MappingRepository();
        // Undeclared exception!
        try {
            mappingRepository0.newEmbeddedClassMetaData((ValueMetaData) null);
            fail("Expecting exception: NullPointerException");

        } catch(NullPointerException e) {
            //
            // no message in exception (getMessage() returned null)
            //
            verifyException("org.apache.openjpa.meta.ClassMetaData", e);
        }
    }

    @Test(timeout = 4000)
    public void test56()  throws Throwable  {
        MappingRepository mappingRepository0 = new MappingRepository();
        mappingRepository0.newMappingInfo((FieldMapping) null);
        assertEquals(7, mappingRepository0.getValidate());
    }

    @Test(timeout = 4000)
    public void test57()  throws Throwable  {
        MappingRepository mappingRepository0 = new MappingRepository();
        // Undeclared exception!
        try {
            mappingRepository0.newMappingInfo((ClassMapping) null);
            fail("Expecting exception: NullPointerException");

        } catch(NullPointerException e) {
            //
            // no message in exception (getMessage() returned null)
            //
            verifyException("org.apache.openjpa.jdbc.meta.MappingRepository", e);
        }
    }

    @Test(timeout = 4000)
    public void test58()  throws Throwable  {
        MappingRepository mappingRepository0 = new MappingRepository();
        // Undeclared exception!
        try {
            mappingRepository0.defaultStrategy((Version) null);
            fail("Expecting exception: NullPointerException");

        } catch(NullPointerException e) {
            //
            // no message in exception (getMessage() returned null)
            //
            verifyException("org.apache.openjpa.jdbc.meta.MappingRepository", e);
        }
    }

    @Test(timeout = 4000)
    public void test59()  throws Throwable  {
        MappingRepository mappingRepository0 = new MappingRepository();
        Order order0 = mappingRepository0.newValueOrder((FieldMetaData) null, false);
        assertEquals(7, mappingRepository0.getValidate());
        assertFalse(order0.isAscending());
    }

    @Test(timeout = 4000)
    public void test60()  throws Throwable  {
        MappingRepository mappingRepository0 = new MappingRepository();
        Class<NanoPrecisionTimestampVersionStrategy> class0 = NanoPrecisionTimestampVersionStrategy.class;
        mappingRepository0.getCachedQueryResultMapping(class0, "gl$vu,`9fTt");
        assertEquals(7, mappingRepository0.getValidate());
    }

    @Test(timeout = 4000)
    public void test61()  throws Throwable  {
        MappingRepository mappingRepository0 = new MappingRepository();
        mappingRepository0.newMappingInfo((ValueMapping) null);
        assertEquals(7, mappingRepository0.getValidate());
    }

    @Test(timeout = 4000)
    public void test62()  throws Throwable  {
        MappingRepository mappingRepository0 = new MappingRepository();
        Class<LogFactoryImpl> class0 = LogFactoryImpl.class;
        // Undeclared exception!
        try {
            mappingRepository0.getMapping(class0, (ClassLoader) null, true);
            fail("Expecting exception: NullPointerException");

        } catch(NullPointerException e) {
            //
            // no message in exception (getMessage() returned null)
            //
            verifyException("org.apache.openjpa.meta.MetaDataRepository", e);
        }
    }

    @Test(timeout = 4000)
    public void test63()  throws Throwable  {
        MappingRepository mappingRepository0 = new MappingRepository();
        mappingRepository0.getDBDictionary();
        assertEquals(7, mappingRepository0.getValidate());
    }

    @Test(timeout = 4000)
    public void test64()  throws Throwable  {
        MappingRepository mappingRepository0 = new MappingRepository();
        // Undeclared exception!
        try {
            mappingRepository0.newDiscriminator((ClassMapping) null);
            fail("Expecting exception: NullPointerException");

        } catch(NullPointerException e) {
            //
            // no message in exception (getMessage() returned null)
            //
            verifyException("org.apache.openjpa.jdbc.meta.Discriminator", e);
        }
    }

    @Test(timeout = 4000)
    public void test65()  throws Throwable  {
        MappingRepository mappingRepository0 = new MappingRepository();
        mappingRepository0.newSequenceMetaData("S;7RO+Yt.(M\"ZUC* dG");
        assertEquals(7, mappingRepository0.getValidate());
    }

    @Test(timeout = 4000)
    public void test66()  throws Throwable  {
        MappingRepository mappingRepository0 = new MappingRepository();
        Class<ClassMapping> class0 = ClassMapping.class;
        ClassMapping[] classMappingArray0 = mappingRepository0.getImplementorMappings(class0, (ClassLoader) null, false);
        assertEquals(7, mappingRepository0.getValidate());
        assertEquals(0, classMappingArray0.length);
    }

    @Test(timeout = 4000)
    public void test67()  throws Throwable  {
        MappingRepository mappingRepository0 = new MappingRepository();
        mappingRepository0.setMappingDefaults((MappingDefaults) null);
        assertEquals(7, mappingRepository0.getValidate());
    }

    @Test(timeout = 4000)
    public void test68()  throws Throwable  {
        MappingRepository mappingRepository0 = new MappingRepository();
        Class<PrivilegedActionException> class0 = PrivilegedActionException.class;
        // Undeclared exception!
        try {
            mappingRepository0.newClassMetaData(class0);
            fail("Expecting exception: NullPointerException");

        } catch(NullPointerException e) {
            //
            // no message in exception (getMessage() returned null)
            //
            verifyException("org.apache.openjpa.meta.ClassMetaData", e);
        }
    }

    @Test(timeout = 4000)
    public void test69()  throws Throwable  {
        MappingRepository mappingRepository0 = new MappingRepository();
        mappingRepository0.newMappingInfo((Discriminator) null);
        assertEquals(7, mappingRepository0.getValidate());
    }

    @Test(timeout = 4000)
    public void test70()  throws Throwable  {
        MappingRepository mappingRepository0 = new MappingRepository();
        // Undeclared exception!
        try {
            mappingRepository0.newVersion((ClassMapping) null);
            fail("Expecting exception: NullPointerException");

        } catch(NullPointerException e) {
            //
            // no message in exception (getMessage() returned null)
            //
            verifyException("org.apache.openjpa.jdbc.meta.Version", e);
        }
    }
}
