/*
 * This file was automatically generated by EvoSuite
 * Wed Jun 03 10:35:36 GMT 2026
 */

package org.apache.openjpa.jdbc.identifier;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.apache.openjpa.conf.OpenJPAConfigurationImpl;
import org.apache.openjpa.jdbc.conf.JDBCConfiguration;
import org.apache.openjpa.jdbc.conf.JDBCConfigurationImpl;
import org.apache.openjpa.jdbc.identifier.DBIdentifier;
import org.apache.openjpa.jdbc.identifier.DBIdentifierUtilImpl;
import org.apache.openjpa.jdbc.identifier.DefaultIdentifierConfiguration;
import org.apache.openjpa.jdbc.identifier.QualifiedDBIdentifier;
import org.apache.openjpa.jdbc.meta.MappingDefaultsImpl;
import org.apache.openjpa.jdbc.schema.Column;
import org.apache.openjpa.jdbc.schema.DynamicSchemaFactory;
import org.apache.openjpa.jdbc.schema.LazySchemaFactory;
import org.apache.openjpa.jdbc.schema.NameSet;
import org.apache.openjpa.jdbc.schema.Schema;
import org.apache.openjpa.jdbc.schema.SchemaGroup;
import org.apache.openjpa.jdbc.schema.Table;
import org.apache.openjpa.jdbc.sql.DB2Dictionary;
import org.apache.openjpa.jdbc.sql.DBDictionary;
import org.apache.openjpa.jdbc.sql.DerbyDictionary;
import org.apache.openjpa.jdbc.sql.FirebirdDictionary;
import org.apache.openjpa.jdbc.sql.FoxProDictionary;
import org.apache.openjpa.jdbc.sql.HSQLDictionary;
import org.apache.openjpa.jdbc.sql.HerdDBDictionary;
import org.apache.openjpa.jdbc.sql.InformixDictionary;
import org.apache.openjpa.jdbc.sql.IngresDictionary;
import org.apache.openjpa.jdbc.sql.InterbaseDictionary;
import org.apache.openjpa.jdbc.sql.MariaDBDictionary;
import org.apache.openjpa.jdbc.sql.PointbaseDictionary;
import org.apache.openjpa.jdbc.sql.PostgresDictionary;
import org.apache.openjpa.jdbc.sql.SQLServerDictionary;
import org.apache.openjpa.jdbc.sql.SolidDBDictionary;
import org.apache.openjpa.lib.identifier.IdentifierConfiguration;
import org.evosuite.runtime.EvoRunnerParameters;

@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true)
public class DBIdentifierUtilImpl_ESTest {

    @Test(timeout = 4000)
    public void test00()  throws Throwable  {
        DefaultIdentifierConfiguration defaultIdentifierConfiguration0 = new DefaultIdentifierConfiguration();
        DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl(defaultIdentifierConfiguration0);
        Table table0 = new Table();
        DBIdentifier dBIdentifier0 = dBIdentifierUtilImpl0.makeNameValid("CASE", table0, 4, 1480, true);
        assertFalse(dBIdentifier0._ignoreCase);
    }

    @Test(timeout = 4000)
    public void test01()  throws Throwable  {
        DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl();
        String string0 = dBIdentifierUtilImpl0.toDBName((DBIdentifier) null);
        assertNull(string0);
    }

    @Test(timeout = 4000)
    public void test02()  throws Throwable  {
        SQLServerDictionary sQLServerDictionary0 = new SQLServerDictionary();
        DBIdentifier dBIdentifier0 = new DBIdentifier("!I`l5>DeJnnSaL2bML", true);
        DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl(sQLServerDictionary0);
        String string0 = dBIdentifierUtilImpl0.toDBName(dBIdentifier0);
        assertEquals("\"!I`l5>DeJnnSaL2bML\"", string0);
    }

    @Test(timeout = 4000)
    public void test03()  throws Throwable  {
        DBIdentifier dBIdentifier0 = DBIdentifier.newColumn("");
        FirebirdDictionary firebirdDictionary0 = new FirebirdDictionary();
        DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl(firebirdDictionary0);
        String string0 = dBIdentifierUtilImpl0.toDBName(dBIdentifier0);
        assertEquals("", string0);
    }

    @Test(timeout = 4000)
    public void test04()  throws Throwable  {
        DefaultIdentifierConfiguration defaultIdentifierConfiguration0 = new DefaultIdentifierConfiguration();
        DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl(defaultIdentifierConfiguration0);
        String string0 = dBIdentifierUtilImpl0.toDBName("", false);
        assertEquals("", string0);
        assertNotNull(string0);
    }

    @Test(timeout = 4000)
    public void test05()  throws Throwable  {
        DefaultIdentifierConfiguration defaultIdentifierConfiguration0 = new DefaultIdentifierConfiguration();
        DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl(defaultIdentifierConfiguration0);
        String string0 = dBIdentifierUtilImpl0.toDBName("");
        assertNotNull(string0);
        assertEquals("", string0);
    }

    @Test(timeout = 4000)
    public void test06()  throws Throwable  {
        FoxProDictionary foxProDictionary0 = new FoxProDictionary();
        DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl(foxProDictionary0);
        String string0 = dBIdentifierUtilImpl0.shorten((String) null, 837);
        assertNull(string0);
    }

    @Test(timeout = 4000)
    public void test07()  throws Throwable  {
        DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl();
        String string0 = dBIdentifierUtilImpl0.shorten("ht@pEDipVI\u0004~y", 1);
        assertEquals("h", string0);
    }

    @Test(timeout = 4000)
    public void test08()  throws Throwable  {
        DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl();
        String string0 = dBIdentifierUtilImpl0.shorten("", 134);
        assertEquals("", string0);
    }

    @Test(timeout = 4000)
    public void test09()  throws Throwable  {
        PointbaseDictionary pointbaseDictionary0 = new PointbaseDictionary();
        DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl(pointbaseDictionary0);
        MappingDefaultsImpl mappingDefaultsImpl0 = new MappingDefaultsImpl();
        DBIdentifier dBIdentifier0 = mappingDefaultsImpl0.getDiscriminatorColumnIdentifier();
        DBIdentifier dBIdentifier1 = dBIdentifierUtilImpl0.getValidUniqueIdentifier(dBIdentifier0, (Table) null, 0);
        assertFalse(dBIdentifier1.getIgnoreCase());
    }

    @Test(timeout = 4000)
    public void test10()  throws Throwable  {
        DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl();
        Schema schema0 = new Schema();
        DBIdentifier dBIdentifier0 = dBIdentifierUtilImpl0.getValidTableIdentifier((DBIdentifier) null, schema0, 63);
        assertNull(dBIdentifier0);
    }

    @Test(timeout = 4000)
    public void test11()  throws Throwable  {
        DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl();
        DBIdentifier.DBIdentifierType dBIdentifier_DBIdentifierType0 = DBIdentifier.DBIdentifierType.TABLE;
        DBIdentifier dBIdentifier0 = dBIdentifierUtilImpl0.fromDBName((String) null, dBIdentifier_DBIdentifierType0);
        Schema schema0 = new Schema();
        DBIdentifier dBIdentifier1 = dBIdentifierUtilImpl0.getValidTableIdentifier(dBIdentifier0, schema0, (-1714));
        assertSame(dBIdentifier0, dBIdentifier1);
    }

    @Test(timeout = 4000)
    public void test12()  throws Throwable  {
        InformixDictionary informixDictionary0 = new InformixDictionary();
        DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl(informixDictionary0);
        DynamicSchemaFactory dynamicSchemaFactory0 = new DynamicSchemaFactory();
        Schema schema0 = dynamicSchemaFactory0.addSchema();
        DBIdentifier dBIdentifier0 = dBIdentifierUtilImpl0.getValidSequenceIdentifier((DBIdentifier) null, schema0, 1173);
        assertNull(dBIdentifier0);
    }

    @Test(timeout = 4000)
    public void test13()  throws Throwable  {
        DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl();
        DBIdentifier dBIdentifier0 = dBIdentifierUtilImpl0.getValidIndexIdentifier((DBIdentifier) null, (Table) null, 710);
        assertNull(dBIdentifier0);
    }

    @Test(timeout = 4000)
    public void test14()  throws Throwable  {
        DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl();
        DBIdentifier dBIdentifier0 = DBIdentifier.newCatalog((String) null, true);
        QualifiedDBIdentifier qualifiedDBIdentifier0 = QualifiedDBIdentifier.getPath(dBIdentifier0);
        QualifiedDBIdentifier qualifiedDBIdentifier1 = (QualifiedDBIdentifier)dBIdentifierUtilImpl0.getValidIndexIdentifier(qualifiedDBIdentifier0, (Table) null, (-1616383149));
        assertTrue(qualifiedDBIdentifier1.isUnqualifiedColumn());
    }

    @Test(timeout = 4000)
    public void test15()  throws Throwable  {
        DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl();
        Table table0 = new Table();
        DBIdentifier dBIdentifier0 = dBIdentifierUtilImpl0.getValidForeignKeyIdentifier((DBIdentifier) null, table0, table0, 1149);
        assertNull(dBIdentifier0);
    }

    @Test(timeout = 4000)
    public void test16()  throws Throwable  {
        DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl();
        DBIdentifier dBIdentifier0 = DBIdentifier.newCatalog((String) null, true);
        QualifiedDBIdentifier qualifiedDBIdentifier0 = QualifiedDBIdentifier.getPath(dBIdentifier0);
        DBIdentifier dBIdentifier1 = dBIdentifierUtilImpl0.getValidForeignKeyIdentifier(qualifiedDBIdentifier0, (Table) null, (Table) null, (-1616383149));
        assertFalse(dBIdentifier1._ignoreCase);
    }

    @Test(timeout = 4000)
    public void test17()  throws Throwable  {
        DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl();
        Table table0 = new Table();
        DBIdentifier dBIdentifier0 = dBIdentifierUtilImpl0.getValidColumnIdentifier((DBIdentifier) null, table0, 2752, false);
        assertNull(dBIdentifier0);
    }

    @Test(timeout = 4000)
    public void test18()  throws Throwable  {
        DefaultIdentifierConfiguration defaultIdentifierConfiguration0 = new DefaultIdentifierConfiguration();
        DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl(defaultIdentifierConfiguration0);
        String string0 = dBIdentifierUtilImpl0.convertAlias((String) null);
        assertNull(string0);
    }

    @Test(timeout = 4000)
    public void test19()  throws Throwable  {
        DBDictionary dBDictionary0 = new DBDictionary();
        DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl(dBDictionary0);
        String string0 = dBIdentifierUtilImpl0.convertAlias("");
        assertEquals("", string0);
    }

    @Test(timeout = 4000)
    public void test20()  throws Throwable  {
        HSQLDictionary hSQLDictionary0 = new HSQLDictionary();
        DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl(hSQLDictionary0);
        Column[] columnArray0 = new Column[1];
        Column column0 = new Column();
        columnArray0[0] = column0;
        String string0 = dBIdentifierUtilImpl0.appendColumns(columnArray0);
        assertNull(string0);
    }

    @Test(timeout = 4000)
    public void test21()  throws Throwable  {
        DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl();
        DBIdentifier dBIdentifier0 = DBIdentifier.newTable("");
        // Undeclared exception!
        try {
            dBIdentifierUtilImpl0.toDBName(dBIdentifier0, false);
            fail("Expecting exception: NullPointerException");

        } catch(NullPointerException e) {
            //
            // no message in exception (getMessage() returned null)
            //
            verifyException("org.apache.openjpa.jdbc.identifier.DBIdentifierUtilImpl", e);
        }
    }

    @Test(timeout = 4000)
    public void test22()  throws Throwable  {
        HSQLDictionary hSQLDictionary0 = new HSQLDictionary();
        DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl(hSQLDictionary0);
        // Undeclared exception!
        try {
            dBIdentifierUtilImpl0.toDBName("OTHER", false);
            fail("Expecting exception: NullPointerException");

        } catch(NullPointerException e) {
            //
            // no message in exception (getMessage() returned null)
            //
            verifyException("org.apache.openjpa.jdbc.identifier.DBIdentifierUtilImpl", e);
        }
    }

    @Test(timeout = 4000)
    public void test23()  throws Throwable  {
        DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl();
        OpenJPAConfigurationImpl openJPAConfigurationImpl0 = new OpenJPAConfigurationImpl();
        // Undeclared exception!
        try {
            dBIdentifierUtilImpl0.setConfiguration(openJPAConfigurationImpl0);
            fail("Expecting exception: ClassCastException");

        } catch(ClassCastException e) {
            //
            // org.apache.openjpa.conf.OpenJPAConfigurationImpl cannot be cast to org.apache.openjpa.jdbc.conf.JDBCConfiguration
            //
            verifyException("org.apache.openjpa.jdbc.identifier.DBIdentifierUtilImpl", e);
        }
    }

    @Test(timeout = 4000)
    public void test24()  throws Throwable  {
        DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl();
        // Undeclared exception!
        try {
            dBIdentifierUtilImpl0.makeIdentifierValid((DBIdentifier) null, (NameSet) null, (-1147), false);
            fail("Expecting exception: NullPointerException");

        } catch(NullPointerException e) {
            //
            // no message in exception (getMessage() returned null)
            //
            verifyException("org.apache.openjpa.jdbc.identifier.DBIdentifierUtilImpl", e);
        }
    }

    @Test(timeout = 4000)
    public void test25()  throws Throwable  {
        MariaDBDictionary mariaDBDictionary0 = new MariaDBDictionary();
        DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl(mariaDBDictionary0);
        DBIdentifier.DBIdentifierType dBIdentifier_DBIdentifierType0 = DBIdentifier.DBIdentifierType.CATALOG;
        DBIdentifier dBIdentifier0 = new DBIdentifier("TIME", dBIdentifier_DBIdentifierType0);
        Schema schema0 = new Schema();
        Table table0 = schema0.addTable(dBIdentifier0, dBIdentifier0);
        // Undeclared exception!
        try {
            dBIdentifierUtilImpl0.getValidUniqueIdentifier(dBIdentifier0, table0, 1000);
            fail("Expecting exception: IllegalArgumentException");

        } catch(IllegalArgumentException e) {
            //
            // Naming rule is null!
            //
            verifyException("org.apache.openjpa.lib.identifier.IdentifierUtilImpl", e);
        }
    }

    @Test(timeout = 4000)
    public void test26()  throws Throwable  {
        DBDictionary dBDictionary0 = new DBDictionary();
        DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl(dBDictionary0);
        DBIdentifier dBIdentifier0 = DBIdentifier.newColumnDefinition("");
        Schema schema0 = new Schema();
        // Undeclared exception!
        try {
            dBIdentifierUtilImpl0.getValidTableIdentifier(dBIdentifier0, schema0, 1396);
            fail("Expecting exception: IllegalArgumentException");

        } catch(IllegalArgumentException e) {
            //
            // Naming rule is null!
            //
            verifyException("org.apache.openjpa.lib.identifier.IdentifierUtilImpl", e);
        }
    }

    @Test(timeout = 4000)
    public void test27()  throws Throwable  {
        FoxProDictionary foxProDictionary0 = new FoxProDictionary();
        DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl(foxProDictionary0);
        DBIdentifier dBIdentifier0 = DBIdentifier.newIndex("0", false);
        DynamicSchemaFactory dynamicSchemaFactory0 = new DynamicSchemaFactory();
        Schema schema0 = dynamicSchemaFactory0.addSchema();
        // Undeclared exception!
        try {
            dBIdentifierUtilImpl0.getValidSequenceIdentifier(dBIdentifier0, schema0, Integer.MAX_VALUE);
            fail("Expecting exception: IllegalArgumentException");

        } catch(IllegalArgumentException e) {
            //
            // Naming rule is null!
            //
            verifyException("org.apache.openjpa.lib.identifier.IdentifierUtilImpl", e);
        }
    }

    @Test(timeout = 4000)
    public void test28()  throws Throwable  {
        MariaDBDictionary mariaDBDictionary0 = new MariaDBDictionary();
        DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl(mariaDBDictionary0);
        DBIdentifier.DBIdentifierType dBIdentifier_DBIdentifierType0 = DBIdentifier.DBIdentifierType.CATALOG;
        DBIdentifier dBIdentifier0 = new DBIdentifier("TIME", dBIdentifier_DBIdentifierType0);
        LazySchemaFactory lazySchemaFactory0 = new LazySchemaFactory();
        Schema schema0 = new Schema(dBIdentifier0, lazySchemaFactory0);
        Table table0 = schema0.addTable(dBIdentifier0, dBIdentifier0);
        // Undeclared exception!
        try {
            dBIdentifierUtilImpl0.getValidIndexIdentifier(dBIdentifier0, table0, 3);
            fail("Expecting exception: IllegalArgumentException");

        } catch(IllegalArgumentException e) {
            //
            // Naming rule is null!
            //
            verifyException("org.apache.openjpa.lib.identifier.IdentifierUtilImpl", e);
        }
    }

    @Test(timeout = 4000)
    public void test29()  throws Throwable  {
        SolidDBDictionary solidDBDictionary0 = new SolidDBDictionary();
        DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl(solidDBDictionary0);
        Column column0 = new Column();
        QualifiedDBIdentifier qualifiedDBIdentifier0 = column0.getQualifiedPath();
        // Undeclared exception!
        try {
            dBIdentifierUtilImpl0.getValidColumnIdentifier(qualifiedDBIdentifier0, (Table) null, 0, false);
            fail("Expecting exception: NullPointerException");

        } catch(NullPointerException e) {
            //
            // no message in exception (getMessage() returned null)
            //
            verifyException("org.apache.openjpa.jdbc.identifier.DBIdentifierUtilImpl", e);
        }
    }

    @Test(timeout = 4000)
    public void test30()  throws Throwable  {
        DBDictionary dBDictionary0 = new DBDictionary();
        DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl(dBDictionary0);
        Table table0 = new Table();
        DBIdentifier dBIdentifier0 = DBIdentifier.newSequence("ALL_CONS_COLUMNS t2 ", false);
        // Undeclared exception!
        try {
            dBIdentifierUtilImpl0.getValidColumnIdentifier(dBIdentifier0, table0, 1133, false);
            fail("Expecting exception: IllegalArgumentException");

        } catch(IllegalArgumentException e) {
            //
            // Naming rule is null!
            //
            verifyException("org.apache.openjpa.lib.identifier.IdentifierUtilImpl", e);
        }
    }

    @Test(timeout = 4000)
    public void test31()  throws Throwable  {
        DerbyDictionary derbyDictionary0 = new DerbyDictionary();
        DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl(derbyDictionary0);
        SchemaGroup schemaGroup0 = new SchemaGroup();
        DBIdentifier dBIdentifier0 = DBIdentifier.newTable("", false);
        DBIdentifier dBIdentifier1 = DBIdentifier.preCombine(dBIdentifier0, "U");
        DBIdentifier dBIdentifier2 = DBIdentifier.toUpper(dBIdentifier1, false);
        Schema schema0 = schemaGroup0.addSchema(dBIdentifier2);
        Table table0 = schema0.addTable(dBIdentifier0, dBIdentifier2);
        Column column0 = table0.addColumn(dBIdentifier1);
        // Undeclared exception!
        try {
            dBIdentifierUtilImpl0.getGeneratedKeySequenceName(column0, 0);
            fail("Expecting exception: StringIndexOutOfBoundsException");

        } catch(StringIndexOutOfBoundsException e) {
        }
    }

    @Test(timeout = 4000)
    public void test32()  throws Throwable  {
        DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl();
        Column column0 = new Column();
        // Undeclared exception!
        try {
            dBIdentifierUtilImpl0.getGeneratedKeySequenceName(column0, 2);
            fail("Expecting exception: NullPointerException");

        } catch(NullPointerException e) {
            //
            // no message in exception (getMessage() returned null)
            //
            verifyException("org.apache.openjpa.jdbc.identifier.DBIdentifierUtilImpl", e);
        }
    }

    @Test(timeout = 4000)
    public void test33()  throws Throwable  {
        DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl((IdentifierConfiguration) null);
        DBIdentifier.DBIdentifierType dBIdentifier_DBIdentifierType0 = DBIdentifier.DBIdentifierType.CONSTANT;
        // Undeclared exception!
        try {
            dBIdentifierUtilImpl0.fromDBName("TINYINT", dBIdentifier_DBIdentifierType0);
            fail("Expecting exception: NullPointerException");

        } catch(NullPointerException e) {
            //
            // no message in exception (getMessage() returned null)
            //
            verifyException("org.apache.openjpa.jdbc.identifier.DBIdentifierUtilImpl", e);
        }
    }

    @Test(timeout = 4000)
    public void test34()  throws Throwable  {
        SolidDBDictionary solidDBDictionary0 = new SolidDBDictionary();
        DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl(solidDBDictionary0);
        DBIdentifier.DBIdentifierType dBIdentifier_DBIdentifierType0 = DBIdentifier.DBIdentifierType.NULL;
        // Undeclared exception!
        try {
            dBIdentifierUtilImpl0.fromDBName("preserve", dBIdentifier_DBIdentifierType0);
            fail("Expecting exception: IllegalStateException");

        } catch(IllegalStateException e) {
            //
            // Cannot modify NULL instance
            //
            verifyException("org.apache.openjpa.jdbc.identifier.DBIdentifier", e);
        }
    }

    @Test(timeout = 4000)
    public void test35()  throws Throwable  {
        DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl();
        DBIdentifier dBIdentifier0 = DBIdentifier.newSchema("NTUJGd#y8S%yWXR");
        // Undeclared exception!
        try {
            dBIdentifierUtilImpl0.convertSchemaCase(dBIdentifier0);
            fail("Expecting exception: NullPointerException");

        } catch(NullPointerException e) {
            //
            // no message in exception (getMessage() returned null)
            //
            verifyException("org.apache.openjpa.jdbc.identifier.DBIdentifierUtilImpl", e);
        }
    }

    @Test(timeout = 4000)
    public void test36()  throws Throwable  {
        MariaDBDictionary mariaDBDictionary0 = new MariaDBDictionary();
        DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl(mariaDBDictionary0);
        DBIdentifier.DBIdentifierType dBIdentifier_DBIdentifierType0 = DBIdentifier.DBIdentifierType.NULL;
        DBIdentifier[] dBIdentifierArray0 = new DBIdentifier[7];
        // Undeclared exception!
        try {
            dBIdentifierUtilImpl0.append(dBIdentifier_DBIdentifierType0, dBIdentifierArray0);
            fail("Expecting exception: IllegalStateException");

        } catch(IllegalStateException e) {
            //
            // Cannot modify NULL instance
            //
            verifyException("org.apache.openjpa.jdbc.identifier.DBIdentifier", e);
        }
    }

    @Test(timeout = 4000)
    public void test37()  throws Throwable  {
        SolidDBDictionary solidDBDictionary0 = new SolidDBDictionary();
        DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl(solidDBDictionary0);
        DBIdentifier.DBIdentifierType dBIdentifier_DBIdentifierType0 = DBIdentifier.DBIdentifierType.FOREIGN_KEY;
        DBIdentifier dBIdentifier0 = DBIdentifier.newIdentifier("DATE", dBIdentifier_DBIdentifierType0, false, true);
        String string0 = dBIdentifierUtilImpl0.toDBName(dBIdentifier0, true);
        assertEquals("\"DATE\"", string0);
    }

    @Test(timeout = 4000)
    public void test38()  throws Throwable  {
        DefaultIdentifierConfiguration defaultIdentifierConfiguration0 = new DefaultIdentifierConfiguration();
        DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl(defaultIdentifierConfiguration0);
        DBIdentifier dBIdentifier0 = DBIdentifier.newColumn("", false);
        DynamicSchemaFactory dynamicSchemaFactory0 = new DynamicSchemaFactory();
        DBIdentifier dBIdentifier1 = dBIdentifierUtilImpl0.makeIdentifierValid(dBIdentifier0, dynamicSchemaFactory0, 97, true);
        assertFalse(dBIdentifier1.equals((Object)dBIdentifier0));
    }

    @Test(timeout = 4000)
    public void test39()  throws Throwable  {
        DefaultIdentifierConfiguration defaultIdentifierConfiguration0 = new DefaultIdentifierConfiguration();
        DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl(defaultIdentifierConfiguration0);
        DBIdentifier dBIdentifier0 = DBIdentifier.newIndex("\">xWEGj9$DA8L@FfaD/\"");
        SchemaGroup schemaGroup0 = new SchemaGroup();
        DBIdentifier dBIdentifier1 = dBIdentifierUtilImpl0.makeIdentifierValid(dBIdentifier0, schemaGroup0, (-2161), false);
        assertSame(dBIdentifier1, dBIdentifier0);
    }

    @Test(timeout = 4000)
    public void test40()  throws Throwable  {
        DB2Dictionary dB2Dictionary0 = new DB2Dictionary();
        DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl(dB2Dictionary0);
        DBIdentifier dBIdentifier0 = DBIdentifier.newSequence("DECIMAL", true);
        // Undeclared exception!
        try {
            dBIdentifierUtilImpl0.makeIdentifierValid(dBIdentifier0, (NameSet) null, 2, true);
            fail("Expecting exception: IllegalArgumentException");

        } catch(IllegalArgumentException e) {
            //
            // Naming rule is null!
            //
            verifyException("org.apache.openjpa.lib.identifier.IdentifierUtilImpl", e);
        }
    }

    @Test(timeout = 4000)
    public void test41()  throws Throwable  {
        DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl();
        DBIdentifier dBIdentifier0 = DBIdentifier.newConstraint("");
        // Undeclared exception!
        try {
            dBIdentifierUtilImpl0.toDBName(dBIdentifier0);
            fail("Expecting exception: NullPointerException");

        } catch(NullPointerException e) {
            //
            // no message in exception (getMessage() returned null)
            //
            verifyException("org.apache.openjpa.jdbc.identifier.DBIdentifierUtilImpl", e);
        }
    }

    @Test(timeout = 4000)
    public void test42()  throws Throwable  {
        HerdDBDictionary herdDBDictionary0 = new HerdDBDictionary();
        DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl(herdDBDictionary0);
        DBIdentifier[] dBIdentifierArray0 = new DBIdentifier[0];
        QualifiedDBIdentifier qualifiedDBIdentifier0 = QualifiedDBIdentifier.newPath(dBIdentifierArray0);
        Table table0 = new Table();
        // Undeclared exception!
        try {
            dBIdentifierUtilImpl0.getValidForeignKeyIdentifier(qualifiedDBIdentifier0, table0, table0, 182);
            fail("Expecting exception: NullPointerException");

        } catch(NullPointerException e) {
            //
            // no message in exception (getMessage() returned null)
            //
            verifyException("org.apache.openjpa.jdbc.identifier.DBIdentifierUtilImpl", e);
        }
    }

    @Test(timeout = 4000)
    public void test43()  throws Throwable  {
        DefaultIdentifierConfiguration defaultIdentifierConfiguration0 = new DefaultIdentifierConfiguration();
        DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl(defaultIdentifierConfiguration0);
        DBIdentifier dBIdentifier0 = DBIdentifier.newCatalog("");
        LazySchemaFactory lazySchemaFactory0 = new LazySchemaFactory();
        Schema schema0 = lazySchemaFactory0.addSchema(dBIdentifier0);
        DBIdentifier dBIdentifier1 = dBIdentifierUtilImpl0.getValidSequenceIdentifier(dBIdentifier0, schema0, 0);
        assertFalse(dBIdentifier1._ignoreCase);
    }

    @Test(timeout = 4000)
    public void test44()  throws Throwable  {
        DefaultIdentifierConfiguration defaultIdentifierConfiguration0 = new DefaultIdentifierConfiguration();
        DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl(defaultIdentifierConfiguration0);
        String string0 = dBIdentifierUtilImpl0.convertAlias("_#ka[fA.v.5FEU$Y");
        assertEquals("_#ka[fA.v.5FEU$Y", string0);
    }

    @Test(timeout = 4000)
    public void test45()  throws Throwable  {
        FoxProDictionary foxProDictionary0 = new FoxProDictionary();
        DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl(foxProDictionary0);
        DBIdentifier.DBIdentifierType dBIdentifier_DBIdentifierType0 = DBIdentifier.DBIdentifierType.TABLE;
        DBIdentifier dBIdentifier0 = DBIdentifier.newIdentifier("S", dBIdentifier_DBIdentifierType0, false, false);
        DBIdentifier dBIdentifier1 = dBIdentifierUtilImpl0.convertSchemaCase(dBIdentifier0);
        assertNotSame(dBIdentifier0, dBIdentifier1);
    }

    @Test(timeout = 4000)
    public void test46()  throws Throwable  {
        HerdDBDictionary herdDBDictionary0 = new HerdDBDictionary();
        DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl(herdDBDictionary0);
        DBIdentifier dBIdentifier0 = DBIdentifier.newConstraint("(OCTET_LENGTH({0}) * 8)");
        DBIdentifier dBIdentifier1 = dBIdentifierUtilImpl0.convertSchemaCase(dBIdentifier0);
        assertFalse(dBIdentifier1.equals((Object)dBIdentifier0));
    }

    @Test(timeout = 4000)
    public void test47()  throws Throwable  {
        DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl();
        DBIdentifier dBIdentifier0 = dBIdentifierUtilImpl0.convertSchemaCase((DBIdentifier) null);
        assertEquals(DBIdentifier.DBIdentifierType.NULL, dBIdentifier0.getType());
    }

    @Test(timeout = 4000)
    public void test48()  throws Throwable  {
        DefaultIdentifierConfiguration defaultIdentifierConfiguration0 = new DefaultIdentifierConfiguration();
        DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl(defaultIdentifierConfiguration0);
        DBIdentifier dBIdentifier0 = DBIdentifier.newTable("R");
        DBIdentifier dBIdentifier1 = dBIdentifierUtilImpl0.convertSchemaCase(dBIdentifier0);
        assertNotSame(dBIdentifier1, dBIdentifier0);
    }

    @Test(timeout = 4000)
    public void test49()  throws Throwable  {
        DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl((IdentifierConfiguration) null);
        DynamicSchemaFactory dynamicSchemaFactory0 = new DynamicSchemaFactory();
        Schema schema0 = dynamicSchemaFactory0.addSchema();
        DBIdentifier dBIdentifier0 = DBIdentifier.newForeignKey(" #$&%!?,.:;\"'");
        Table table0 = schema0.addTable(dBIdentifier0, dBIdentifier0);
        Column column0 = table0.addColumn(dBIdentifier0);
        QualifiedDBIdentifier qualifiedDBIdentifier0 = (QualifiedDBIdentifier)dBIdentifierUtilImpl0.getGeneratedKeySequenceName(column0, 32);
        assertFalse(qualifiedDBIdentifier0.isUnqualifiedColumn());
    }

    @Test(timeout = 4000)
    public void test50()  throws Throwable  {
        DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl();
        Schema schema0 = new Schema();
        DBIdentifier dBIdentifier0 = DBIdentifier.newColumnDefinition("nGkUaSCMUx2LS");
        Table table0 = new Table(dBIdentifier0, schema0);
        Column column0 = table0.addColumn(dBIdentifier0, dBIdentifier0);
        DBIdentifier dBIdentifier1 = dBIdentifierUtilImpl0.getGeneratedKeySequenceName(column0, 64);
        assertFalse(dBIdentifier1._ignoreCase);
    }

    @Test(timeout = 4000)
    public void test51()  throws Throwable  {
        IngresDictionary ingresDictionary0 = new IngresDictionary();
        DBIdentifier dBIdentifier0 = DBIdentifier.newConstraint("}]:e3.[P}o}", false);
        DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl(ingresDictionary0);
        String string0 = dBIdentifierUtilImpl0.delimit(dBIdentifier0, true);
        assertEquals("\"}]:e3\".\"[P}o}\"", string0);
    }

    @Test(timeout = 4000)
    public void test52()  throws Throwable  {
        DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl();
        DBIdentifier dBIdentifier0 = DBIdentifier.newConstraint("PH_:>yM.K");
        // Undeclared exception!
        try {
            dBIdentifierUtilImpl0.delimit(dBIdentifier0, false);
            fail("Expecting exception: NullPointerException");

        } catch(NullPointerException e) {
            //
            // no message in exception (getMessage() returned null)
            //
            verifyException("org.apache.openjpa.lib.identifier.IdentifierUtilImpl", e);
        }
    }

    @Test(timeout = 4000)
    public void test53()  throws Throwable  {
        FoxProDictionary foxProDictionary0 = new FoxProDictionary();
        DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl(foxProDictionary0);
        DBIdentifier.DBIdentifierType dBIdentifier_DBIdentifierType0 = DBIdentifier.DBIdentifierType.TABLE;
        DBIdentifier dBIdentifier0 = DBIdentifier.newIdentifier("S", dBIdentifier_DBIdentifierType0, false, false);
        // Undeclared exception!
        try {
            dBIdentifierUtilImpl0.delimit(dBIdentifier0, true);
            fail("Expecting exception: NullPointerException");

        } catch(NullPointerException e) {
            //
            // no message in exception (getMessage() returned null)
            //
            verifyException("org.apache.openjpa.lib.identifier.IdentifierUtilImpl", e);
        }
    }

    @Test(timeout = 4000)
    public void test54()  throws Throwable  {
        DefaultIdentifierConfiguration defaultIdentifierConfiguration0 = new DefaultIdentifierConfiguration();
        DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl(defaultIdentifierConfiguration0);
        DBIdentifier dBIdentifier0 = DBIdentifier.newColumn("", false);
        String string0 = dBIdentifierUtilImpl0.delimit(dBIdentifier0, false);
        assertEquals("", string0);
    }

    @Test(timeout = 4000)
    public void test55()  throws Throwable  {
        DefaultIdentifierConfiguration defaultIdentifierConfiguration0 = new DefaultIdentifierConfiguration();
        DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl(defaultIdentifierConfiguration0);
        DBIdentifier dBIdentifier0 = DBIdentifier.newCatalog("");
        String string0 = dBIdentifierUtilImpl0.delimit(dBIdentifier0, true);
        assertEquals("", string0);
    }

    @Test(timeout = 4000)
    public void test56()  throws Throwable  {
        PostgresDictionary postgresDictionary0 = new PostgresDictionary();
        DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl(postgresDictionary0);
        DBIdentifier.DBIdentifierType dBIdentifier_DBIdentifierType0 = DBIdentifier.DBIdentifierType.FOREIGN_KEY;
        String[] stringArray0 = new String[0];
        DBIdentifier dBIdentifier0 = DBIdentifier.combine(dBIdentifier_DBIdentifierType0, stringArray0);
        Column column0 = new Column(dBIdentifier0, (Table) null);
        Column[] columnArray0 = new Column[9];
        columnArray0[0] = column0;
        columnArray0[1] = column0;
        columnArray0[2] = column0;
        columnArray0[3] = column0;
        columnArray0[4] = column0;
        columnArray0[5] = column0;
        columnArray0[6] = column0;
        columnArray0[7] = column0;
        columnArray0[8] = column0;
        String string0 = dBIdentifierUtilImpl0.appendColumns(columnArray0);
        assertEquals("null, null, null, null, null, null, null, null, null", string0);
        assertNotNull(string0);
    }

    @Test(timeout = 4000)
    public void test57()  throws Throwable  {
        PostgresDictionary postgresDictionary0 = new PostgresDictionary();
        DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl(postgresDictionary0);
        Column[] columnArray0 = new Column[9];
        // Undeclared exception!
        try {
            dBIdentifierUtilImpl0.appendColumns(columnArray0);
            fail("Expecting exception: NullPointerException");

        } catch(NullPointerException e) {
            //
            // no message in exception (getMessage() returned null)
            //
            verifyException("org.apache.openjpa.jdbc.identifier.DBIdentifierUtilImpl", e);
        }
    }

    @Test(timeout = 4000)
    public void test58()  throws Throwable  {
        DefaultIdentifierConfiguration defaultIdentifierConfiguration0 = new DefaultIdentifierConfiguration();
        DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl(defaultIdentifierConfiguration0);
        Column[] columnArray0 = new Column[0];
        String string0 = dBIdentifierUtilImpl0.appendColumns(columnArray0);
        assertEquals("", string0);
    }

    @Test(timeout = 4000)
    public void test59()  throws Throwable  {
        DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl((IdentifierConfiguration) null);
        String string0 = dBIdentifierUtilImpl0.appendColumns((Column[]) null);
        assertEquals("", string0);
    }

    @Test(timeout = 4000)
    public void test60()  throws Throwable  {
        DefaultIdentifierConfiguration defaultIdentifierConfiguration0 = new DefaultIdentifierConfiguration();
        DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl(defaultIdentifierConfiguration0);
        DBIdentifier dBIdentifier0 = DBIdentifier.newTable("R");
        DBIdentifier.DBIdentifierType dBIdentifier_DBIdentifierType0 = DBIdentifier.DBIdentifierType.FOREIGN_KEY;
        DBIdentifier[] dBIdentifierArray0 = new DBIdentifier[4];
        dBIdentifierArray0[0] = dBIdentifier0;
        dBIdentifierArray0[1] = dBIdentifier0;
        dBIdentifierArray0[2] = dBIdentifier0;
        dBIdentifierArray0[3] = dBIdentifier0;
        DBIdentifier dBIdentifier1 = dBIdentifierUtilImpl0.append(dBIdentifier_DBIdentifierType0, dBIdentifierArray0);
        assertEquals(DBIdentifier.DBIdentifierType.FOREIGN_KEY, dBIdentifier1.getType());
    }

    @Test(timeout = 4000)
    public void test61()  throws Throwable  {
        DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl();
        DBIdentifier.DBIdentifierType dBIdentifier_DBIdentifierType0 = DBIdentifier.DBIdentifierType.TABLE;
        DBIdentifier[] dBIdentifierArray0 = new DBIdentifier[0];
        DBIdentifier dBIdentifier0 = dBIdentifierUtilImpl0.append(dBIdentifier_DBIdentifierType0, dBIdentifierArray0);
        assertFalse(dBIdentifier0._ignoreCase);
    }

    @Test(timeout = 4000)
    public void test62()  throws Throwable  {
        DefaultIdentifierConfiguration defaultIdentifierConfiguration0 = new DefaultIdentifierConfiguration();
        DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl(defaultIdentifierConfiguration0);
        DBIdentifier.DBIdentifierType dBIdentifier_DBIdentifierType0 = DBIdentifier.DBIdentifierType.FOREIGN_KEY;
        DBIdentifier[] dBIdentifierArray0 = new DBIdentifier[4];
        // Undeclared exception!
        try {
            dBIdentifierUtilImpl0.append(dBIdentifier_DBIdentifierType0, dBIdentifierArray0);
            fail("Expecting exception: NullPointerException");

        } catch(NullPointerException e) {
            //
            // no message in exception (getMessage() returned null)
            //
            verifyException("org.apache.openjpa.jdbc.identifier.DBIdentifierUtilImpl", e);
        }
    }

    @Test(timeout = 4000)
    public void test63()  throws Throwable  {
        DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl((IdentifierConfiguration) null);
        DBIdentifier.DBIdentifierType dBIdentifier_DBIdentifierType0 = DBIdentifier.DBIdentifierType.CONSTRAINT;
        DBIdentifier dBIdentifier0 = dBIdentifierUtilImpl0.append(dBIdentifier_DBIdentifierType0, (DBIdentifier[]) null);
        assertEquals(DBIdentifier.DBIdentifierType.NULL, dBIdentifier0.getType());
    }

    @Test(timeout = 4000)
    public void test64()  throws Throwable  {
        DB2Dictionary dB2Dictionary0 = new DB2Dictionary();
        DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl(dB2Dictionary0);
        DBIdentifier.DBIdentifierType dBIdentifier_DBIdentifierType0 = DBIdentifier.DBIdentifierType.DEFAULT;
        DBIdentifier dBIdentifier0 = dBIdentifierUtilImpl0.fromDBName("UPPER({0})", dBIdentifier_DBIdentifierType0);
        assertEquals(DBIdentifier.DBIdentifierType.DEFAULT, dBIdentifier0.getType());
    }

    @Test(timeout = 4000)
    public void test65()  throws Throwable  {
        DefaultIdentifierConfiguration defaultIdentifierConfiguration0 = new DefaultIdentifierConfiguration();
        DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl(defaultIdentifierConfiguration0);
        DBIdentifier.DBIdentifierType dBIdentifier_DBIdentifierType0 = DBIdentifier.DBIdentifierType.FOREIGN_KEY;
        DBIdentifier dBIdentifier0 = dBIdentifierUtilImpl0.fromDBName("", dBIdentifier_DBIdentifierType0);
        assertEquals(DBIdentifier.DBIdentifierType.FOREIGN_KEY, dBIdentifier0.getType());
        assertFalse(dBIdentifier0.isNameDelimited());
        assertFalse(dBIdentifier0._ignoreCase);
    }

    @Test(timeout = 4000)
    public void test66()  throws Throwable  {
        DefaultIdentifierConfiguration defaultIdentifierConfiguration0 = new DefaultIdentifierConfiguration();
        DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl(defaultIdentifierConfiguration0);
        String string0 = dBIdentifierUtilImpl0.toDBName("lower");
        assertNotNull(string0);
        assertEquals("lower", string0);
    }

    @Test(timeout = 4000)
    public void test67()  throws Throwable  {
        DefaultIdentifierConfiguration defaultIdentifierConfiguration0 = new DefaultIdentifierConfiguration();
        DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl(defaultIdentifierConfiguration0);
        String string0 = dBIdentifierUtilImpl0.toDBName("R", false);
        assertNotNull(string0);
        assertEquals("R", string0);
    }

    @Test(timeout = 4000)
    public void test68()  throws Throwable  {
        HerdDBDictionary herdDBDictionary0 = new HerdDBDictionary();
        DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl(herdDBDictionary0);
        DBIdentifier dBIdentifier0 = DBIdentifier.newConstraint("(OCTET_LENGTH({0}) * 8)");
        String string0 = dBIdentifierUtilImpl0.toDBName(dBIdentifier0, true);
        assertEquals("`(OCTET_LENGTH({0}) * 8)`", string0);
    }

    @Test(timeout = 4000)
    public void test69()  throws Throwable  {
        DefaultIdentifierConfiguration defaultIdentifierConfiguration0 = new DefaultIdentifierConfiguration();
        DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl(defaultIdentifierConfiguration0);
        DBIdentifier dBIdentifier0 = DBIdentifier.newIndex("");
        String string0 = dBIdentifierUtilImpl0.toDBName(dBIdentifier0, true);
        assertEquals("", string0);
    }

    @Test(timeout = 4000)
    public void test70()  throws Throwable  {
        DefaultIdentifierConfiguration defaultIdentifierConfiguration0 = new DefaultIdentifierConfiguration();
        DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl(defaultIdentifierConfiguration0);
        DBIdentifier dBIdentifier0 = DBIdentifier.newTable("R");
        String string0 = dBIdentifierUtilImpl0.toDBName(dBIdentifier0, false);
        assertEquals("R", string0);
    }

    @Test(timeout = 4000)
    public void test71()  throws Throwable  {
        DefaultIdentifierConfiguration defaultIdentifierConfiguration0 = new DefaultIdentifierConfiguration();
        DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl(defaultIdentifierConfiguration0);
        String[] stringArray0 = new String[9];
        DBIdentifier dBIdentifier0 = DBIdentifier.newTable(stringArray0[1]);
        String string0 = dBIdentifierUtilImpl0.toDBName(dBIdentifier0, false);
        String string1 = dBIdentifierUtilImpl0.toDBName(string0, false);
        assertNull(string1);
    }

    @Test(timeout = 4000)
    public void test72()  throws Throwable  {
        DefaultIdentifierConfiguration defaultIdentifierConfiguration0 = new DefaultIdentifierConfiguration();
        DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl(defaultIdentifierConfiguration0);
        DBIdentifier dBIdentifier0 = DBIdentifier.newTable("R");
        Table table0 = new Table();
        // Undeclared exception!
        try {
            dBIdentifierUtilImpl0.makeIdentifierValid(dBIdentifier0, table0, (-5), true);
            fail("Expecting exception: ClassCastException");

        } catch(ClassCastException e) {
            //
            // org.apache.openjpa.jdbc.schema.Table cannot be cast to org.apache.openjpa.jdbc.schema.SchemaGroup
            //
            verifyException("org.apache.openjpa.jdbc.identifier.DBIdentifierUtilImpl", e);
        }
    }

    @Test(timeout = 4000)
    public void test73()  throws Throwable  {
        DefaultIdentifierConfiguration defaultIdentifierConfiguration0 = new DefaultIdentifierConfiguration();
        DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl(defaultIdentifierConfiguration0);
        DBIdentifier dBIdentifier0 = DBIdentifier.newTable("R");
        Table table0 = new Table();
        DBIdentifier dBIdentifier1 = dBIdentifierUtilImpl0.getValidColumnIdentifier(dBIdentifier0, table0, (-5), false);
        assertTrue(dBIdentifier1.equals((Object)dBIdentifier0));
    }

    @Test(timeout = 4000)
    public void test74()  throws Throwable  {
        DefaultIdentifierConfiguration defaultIdentifierConfiguration0 = new DefaultIdentifierConfiguration();
        DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl(defaultIdentifierConfiguration0);
        DBIdentifier dBIdentifier0 = dBIdentifierUtilImpl0.makeNameValid("O2IK{>64i(74", (NameSet) null, 3391, 3391, true);
        assertFalse(dBIdentifier0._ignoreCase);
    }

    @Test(timeout = 4000)
    public void test75()  throws Throwable  {
        HSQLDictionary hSQLDictionary0 = new HSQLDictionary();
        DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl(hSQLDictionary0);
        NameSet nameSet0 = new NameSet();
        // Undeclared exception!
        try {
            dBIdentifierUtilImpl0.makeNameValid("upper", nameSet0, 1906, 3, false);
            fail("Expecting exception: IllegalArgumentException");

        } catch(IllegalArgumentException e) {
            //
            // Naming rule is null!
            //
            verifyException("org.apache.openjpa.lib.identifier.IdentifierUtilImpl", e);
        }
    }

    @Test(timeout = 4000)
    public void test76()  throws Throwable  {
        DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl();
        NameSet nameSet0 = new NameSet();
        // Undeclared exception!
        try {
            dBIdentifierUtilImpl0.makeNameValid("eY=cdf|zR#nj;f", nameSet0, 2, 2, false);
            fail("Expecting exception: NullPointerException");

        } catch(NullPointerException e) {
            //
            // no message in exception (getMessage() returned null)
            //
            verifyException("org.apache.openjpa.jdbc.identifier.DBIdentifierUtilImpl", e);
        }
    }

    @Test(timeout = 4000)
    public void test77()  throws Throwable  {
        DefaultIdentifierConfiguration defaultIdentifierConfiguration0 = new DefaultIdentifierConfiguration();
        DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl(defaultIdentifierConfiguration0);
        Table table0 = new Table();
        DBIdentifier dBIdentifier0 = dBIdentifierUtilImpl0.makeNameValid("_#ka[fA.v.5FEU$Y", table0, (-5), 1480, true);
        DBIdentifier dBIdentifier1 = dBIdentifierUtilImpl0.convertSchemaCase(dBIdentifier0);
        assertEquals(DBIdentifier.DBIdentifierType.DEFAULT, dBIdentifier1.getType());

        DBIdentifier dBIdentifier2 = dBIdentifierUtilImpl0.makeIdentifierValid(dBIdentifier1, table0, 253, true);
        assertTrue(dBIdentifier2.equals((Object)dBIdentifier1));
        assertFalse(dBIdentifier2.equals((Object)dBIdentifier0));
    }

    @Test(timeout = 4000)
    public void test78()  throws Throwable  {
        DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl();
        LazySchemaFactory lazySchemaFactory0 = new LazySchemaFactory();
        // Undeclared exception!
        try {
            dBIdentifierUtilImpl0.makeNameValid("DynamicEnhancementAgent", lazySchemaFactory0, 1, 1, false);
            fail("Expecting exception: NullPointerException");

        } catch(NullPointerException e) {
            //
            // no message in exception (getMessage() returned null)
            //
            verifyException("org.apache.openjpa.jdbc.identifier.DBIdentifierUtilImpl", e);
        }
    }

    @Test(timeout = 4000)
    public void test79()  throws Throwable  {
        PostgresDictionary postgresDictionary0 = new PostgresDictionary();
        DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl(postgresDictionary0);
        DBIdentifier.DBIdentifierType dBIdentifier_DBIdentifierType0 = DBIdentifier.DBIdentifierType.FOREIGN_KEY;
        String[] stringArray0 = new String[0];
        DBIdentifier dBIdentifier0 = DBIdentifier.combine(dBIdentifier_DBIdentifierType0, stringArray0);
        QualifiedDBIdentifier qualifiedDBIdentifier0 = QualifiedDBIdentifier.getPath(dBIdentifier0);
        LazySchemaFactory lazySchemaFactory0 = new LazySchemaFactory();
        Schema schema0 = lazySchemaFactory0.addSchema((DBIdentifier) qualifiedDBIdentifier0);
        DBIdentifier dBIdentifier1 = dBIdentifierUtilImpl0.getValidTableIdentifier(qualifiedDBIdentifier0, schema0, 587);
        assertFalse(dBIdentifier1._ignoreCase);
    }

    @Test(timeout = 4000)
    public void test80()  throws Throwable  {
        PostgresDictionary postgresDictionary0 = new PostgresDictionary();
        DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl(postgresDictionary0);
        DBIdentifier.DBIdentifierType dBIdentifier_DBIdentifierType0 = DBIdentifier.DBIdentifierType.FOREIGN_KEY;
        String[] stringArray0 = new String[0];
        DBIdentifier dBIdentifier0 = DBIdentifier.combine(dBIdentifier_DBIdentifierType0, stringArray0);
        Column column0 = new Column(dBIdentifier0, (Table) null);
        QualifiedDBIdentifier qualifiedDBIdentifier0 = column0.getQualifiedPath();
        LazySchemaFactory lazySchemaFactory0 = new LazySchemaFactory();
        Schema schema0 = lazySchemaFactory0.addSchema((DBIdentifier) qualifiedDBIdentifier0);
        // Undeclared exception!
        try {
            dBIdentifierUtilImpl0.getValidTableIdentifier(qualifiedDBIdentifier0, schema0, 592);
            fail("Expecting exception: NullPointerException");

        } catch(NullPointerException e) {
            //
            // no message in exception (getMessage() returned null)
            //
            verifyException("org.apache.openjpa.jdbc.identifier.DBIdentifierUtilImpl", e);
        }
    }

    @Test(timeout = 4000)
    public void test81()  throws Throwable  {
        DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl((IdentifierConfiguration) null);
        MappingDefaultsImpl mappingDefaultsImpl0 = new MappingDefaultsImpl();
        DBIdentifier dBIdentifier0 = mappingDefaultsImpl0.getNullIndicatorColumnIdentifier();
        DBIdentifier dBIdentifier1 = dBIdentifierUtilImpl0.getValidSequenceIdentifier(dBIdentifier0, (Schema) null, 1913);
        assertEquals(DBIdentifier.DBIdentifierType.NULL, dBIdentifier1.getType());
    }

    @Test(timeout = 4000)
    public void test82()  throws Throwable  {
        DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl((IdentifierConfiguration) null);
        DBIdentifier dBIdentifier0 = DBIdentifier.newSequence("_w{}L!6_0");
        Schema schema0 = new Schema();
        // Undeclared exception!
        try {
            dBIdentifierUtilImpl0.getValidSequenceIdentifier(dBIdentifier0, schema0, 0);
            fail("Expecting exception: NullPointerException");

        } catch(NullPointerException e) {
            //
            // no message in exception (getMessage() returned null)
            //
            verifyException("org.apache.openjpa.jdbc.identifier.DBIdentifierUtilImpl", e);
        }
    }

    @Test(timeout = 4000)
    public void test83()  throws Throwable  {
        DefaultIdentifierConfiguration defaultIdentifierConfiguration0 = new DefaultIdentifierConfiguration();
        DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl(defaultIdentifierConfiguration0);
        String[] stringArray0 = new String[9];
        Table table0 = new Table();
        DBIdentifier.DBIdentifierType dBIdentifier_DBIdentifierType0 = DBIdentifier.DBIdentifierType.FOREIGN_KEY;
        DBIdentifier dBIdentifier0 = dBIdentifierUtilImpl0.fromDBName(stringArray0[8], dBIdentifier_DBIdentifierType0);
        DBIdentifier dBIdentifier1 = dBIdentifierUtilImpl0.getValidIndexIdentifier(dBIdentifier0, table0, (-5));
        assertSame(dBIdentifier1, dBIdentifier0);
    }

    @Test(timeout = 4000)
    public void test84()  throws Throwable  {
        FoxProDictionary foxProDictionary0 = new FoxProDictionary();
        DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl(foxProDictionary0);
        DBIdentifier.DBIdentifierType dBIdentifier_DBIdentifierType0 = DBIdentifier.DBIdentifierType.TABLE;
        DBIdentifier dBIdentifier0 = DBIdentifier.newIdentifier("CURRENT_DATE", dBIdentifier_DBIdentifierType0, false, false);
        // Undeclared exception!
        try {
            dBIdentifierUtilImpl0.getValidIndexIdentifier(dBIdentifier0, (Table) null, 30);
            fail("Expecting exception: NullPointerException");

        } catch(NullPointerException e) {
            //
            // no message in exception (getMessage() returned null)
            //
            verifyException("org.apache.openjpa.jdbc.identifier.DBIdentifierUtilImpl", e);
        }
    }

    @Test(timeout = 4000)
    public void test85()  throws Throwable  {
        DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl();
        DBIdentifier dBIdentifier0 = dBIdentifierUtilImpl0.getValidUniqueIdentifier((DBIdentifier) null, (Table) null, (-1147));
        assertNull(dBIdentifier0);
    }

    @Test(timeout = 4000)
    public void test86()  throws Throwable  {
        DefaultIdentifierConfiguration defaultIdentifierConfiguration0 = new DefaultIdentifierConfiguration();
        DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl(defaultIdentifierConfiguration0);
        DBIdentifier dBIdentifier0 = DBIdentifier.newTable("R");
        Table table0 = new Table();
        // Undeclared exception!
        try {
            dBIdentifierUtilImpl0.getValidUniqueIdentifier(dBIdentifier0, table0, (-5));
            fail("Expecting exception: NullPointerException");

        } catch(NullPointerException e) {
            //
            // no message in exception (getMessage() returned null)
            //
            verifyException("org.apache.openjpa.jdbc.identifier.DBIdentifierUtilImpl", e);
        }
    }

    @Test(timeout = 4000)
    public void test87()  throws Throwable  {
        FoxProDictionary foxProDictionary0 = new FoxProDictionary();
        DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl(foxProDictionary0);
        DBIdentifier.DBIdentifierType dBIdentifier_DBIdentifierType0 = DBIdentifier.DBIdentifierType.TABLE;
        QualifiedDBIdentifier qualifiedDBIdentifier0 = (QualifiedDBIdentifier)DBIdentifier.newIdentifier("S", dBIdentifier_DBIdentifierType0, false, false);
        DBIdentifier dBIdentifier0 = qualifiedDBIdentifier0.getSchemaName();
        DBIdentifier dBIdentifier1 = dBIdentifierUtilImpl0.getValidForeignKeyIdentifier(dBIdentifier0, (Table) null, (Table) null, 1630);
        assertFalse(dBIdentifier1._ignoreCase);
    }

    @Test(timeout = 4000)
    public void test88()  throws Throwable  {
        MariaDBDictionary mariaDBDictionary0 = new MariaDBDictionary();
        DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl(mariaDBDictionary0);
        DBIdentifier.DBIdentifierType dBIdentifier_DBIdentifierType0 = DBIdentifier.DBIdentifierType.CATALOG;
        DBIdentifier dBIdentifier0 = new DBIdentifier("TIME", dBIdentifier_DBIdentifierType0);
        LazySchemaFactory lazySchemaFactory0 = new LazySchemaFactory();
        Schema schema0 = new Schema(dBIdentifier0, lazySchemaFactory0);
        Table table0 = schema0.addTable(dBIdentifier0, dBIdentifier0);
        // Undeclared exception!
        try {
            dBIdentifierUtilImpl0.getValidForeignKeyIdentifier(dBIdentifier0, table0, table0, 28);
            fail("Expecting exception: IllegalArgumentException");

        } catch(IllegalArgumentException e) {
            //
            // Naming rule is null!
            //
            verifyException("org.apache.openjpa.lib.identifier.IdentifierUtilImpl", e);
        }
    }

    @Test(timeout = 4000)
    public void test89()  throws Throwable  {
        DefaultIdentifierConfiguration defaultIdentifierConfiguration0 = new DefaultIdentifierConfiguration();
        DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl(defaultIdentifierConfiguration0);
        String[] stringArray0 = new String[9];
        DBIdentifier dBIdentifier0 = DBIdentifier.newTable(stringArray0[1]);
        Table table0 = new Table();
        DBIdentifier dBIdentifier1 = dBIdentifierUtilImpl0.getValidColumnIdentifier(dBIdentifier0, table0, (-5), false);
        assertSame(dBIdentifier1, dBIdentifier0);
    }

    @Test(timeout = 4000)
    public void test90()  throws Throwable  {
        PostgresDictionary postgresDictionary0 = new PostgresDictionary();
        DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl(postgresDictionary0);
        JDBCConfigurationImpl jDBCConfigurationImpl0 = new JDBCConfigurationImpl((JDBCConfiguration) null);
        dBIdentifierUtilImpl0.setConfiguration(jDBCConfigurationImpl0);
        JDBCConfiguration jDBCConfiguration0 = dBIdentifierUtilImpl0.getConfiguration();
        assertEquals(0, jDBCConfiguration0.getScriptsActionConstant());
    }

    @Test(timeout = 4000)
    public void test91()  throws Throwable  {
        InterbaseDictionary interbaseDictionary0 = new InterbaseDictionary();
        DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl(interbaseDictionary0);
        // Undeclared exception!
        dBIdentifierUtilImpl0.shorten("", (-1207));
    }

    @Test(timeout = 4000)
    public void test92()  throws Throwable  {
        DefaultIdentifierConfiguration defaultIdentifierConfiguration0 = new DefaultIdentifierConfiguration();
        DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl(defaultIdentifierConfiguration0);
        JDBCConfiguration jDBCConfiguration0 = dBIdentifierUtilImpl0.getConfiguration();
        assertNull(jDBCConfiguration0);
    }

    @Test(timeout = 4000)
    public void test93()  throws Throwable  {
        DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl();
        // Undeclared exception!
        try {
            dBIdentifierUtilImpl0.toDBName("mSZ=in\u0006)");
            fail("Expecting exception: NullPointerException");

        } catch(NullPointerException e) {
            //
            // no message in exception (getMessage() returned null)
            //
            verifyException("org.apache.openjpa.jdbc.identifier.DBIdentifierUtilImpl", e);
        }
    }
}
